# Generated by Django 5.2.5 on 2025-08-08 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='service',
            new_name='relation',
        ),
    ]
